# 例外の仕組み
- try-catch-finally節の中で返り値を規定すると、関数の戻り値はtry節あるいはcatch節のものになったあと、最終的にfinally節のものに置き換わる。

```
public class Main {
    public static void main(String[] args) {
        System.out.println(getNum());
    }

    static int getNum() {
        try {
            throw new Exception();
        }
        catch (Exception e) {
            return 10;
        }
        finally {
            return 20;
        }
    }
}
```

出力結果：20  

- finallyブロックで返り値の変更のみ行い、returnしない場合は変更は反映されない。  
ただしこれはintやStringなどのプリミティブ型の場合で、参照型の返り値であれば変更が反映される。
```
public class Main {
    public static void main(String[] args) {
        System.out.println(getNum());
    }

    static int getNum() {
        int val = 0;
        try {
            throw new Exception();
        }
        catch (Exception e) {
            val = 10;
            return val;
        }
        finally {
            val += 20;
        }
    }
}
```

- 検査例外...コンパイラが例外処理を記述したかどうかをチェックする例外。Javaの例外クラスは基本的にこちら。
- 非検査例外...コンパイラによるチェックが行われない例外。RuntimeExceptionとその子クラスが該当。